pluginManagement {
    repositories {
        // ForgeGradle / mixingradle 插件仓库
        maven { url 'https://maven.minecraftforge.net/' }
        maven { url 'https://repo.spongepowered.org/repository/maven-public/' }
        maven { url 'https://maven.izzel.io/releases' }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = 'paperarc'

include 'common'